engines:
  rubocop:
    enabled: true
  golint:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
exclude_paths:
- spec/**/*
- vendor/**/*
- public/**/*
